FROM golang:1.20.7-alpine3.18 as builder

WORKDIR /project/pcr-backend

COPY go.* ./

RUN go mod download

COPY . .
RUN go build -o /project/pcr-backend/build/main cmd/main.go

FROM alpine:latest
COPY --from=builder /project/pcr-backend/build/main /app/build/main
COPY templates /app/templates
COPY migrations /app/migrations

EXPOSE 8080

ENV GIN_MODE=release

ENTRYPOINT [ "/app/build/main", "--prod" ]