FROM golang:alpine AS builder

WORKDIR /project/pcr-backend

COPY go.* ./

RUN go mod download

COPY . .
RUN go build -o /project/pcr-backend/build/main cmd/main.go

FROM alpine:latest
COPY --from=builder /project/pcr-backend/build/main /app/build/main
COPY templates /templates
EXPOSE 8080
ENTRYPOINT [ "/app/build/main", "--prod" ]