apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pcr
  labels:
    app: postgres-container
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-container