-- Fill the analysis table with data
INSERT INTO analyses (analysis_id, ready_mix, display_name) VALUES
('CMVQPA',TRUE,''),
('CMVQPE',TRUE,''),
('CMVQPEP',TRUE,''),
('CMVQPFW',TRUE,''),
('CMVQPL',TRUE,''),
('CMVQPRES',TRUE,''),
('CMVQPS',TRUE,''),
('CMVQPU',TRUE,''),
('CMVQPX',TRUE,''),
('EBVQPE',TRUE,''),
('EBVQPEP',TRUE,''),
('EBVQPS',TRUE,''),
('EBVQPL',TRUE,''),
('EBVQPX ',TRUE,''),
('HEVQPE',FALSE,''),
('HEVQPST',FALSE,''),
('HEVQPX',FALSE,''),
('PNJIQPBAL',TRUE,''),
('PNJIQPRES',TRUE,''),
('PNJIQPX',TRUE,''),
('CHLAPPA',FALSE,''),
('CHLAPPBAL',FALSE,''),
('CHLAPPX',FALSE,''),
('LEGPBAL',FALSE,''),
('LEGPX',FALSE,''),
('MYPPA',FALSE,''),
('MYPPBAL',FALSE,''),
('MYPPX',FALSE,''),
('TBCPMAG',TRUE,''),
('TBCPP',TRUE,''),
('TBCPPE',TRUE,''),
('TBCPRES',TRUE,''),
('TBCPSPU',TRUE,''),
('TBCPU',TRUE,''),
('TBCPX',TRUE,'');