INSERT INTO analyses (
    analyt,
    material,
    assay,
    ready_mix,
    is_active
)
VALUES 
('CMV','EP','PL (plasma)',TRUE,TRUE),
('CMV','E','WB (whole blood)',TRUE,TRUE),
('CMV','Liq','CSF',TRUE,TRUE),
('CMV','U','U (urine)',TRUE,TRUE),
('CMV','ABN','BS (buccal swab)',TRUE,TRUE),
('CMV','AB','BS (buccal swab)',TRUE,TRUE),
('CMV','Fruchtwasser','AF (amniotic fluid)',TRUE,TRUE),
('CMV','Stuhl','Generic',TRUE,TRUE),
('CMV','VB','Generic',TRUE,TRUE),
('CMV','S','Generic',TRUE,TRUE),
('CMV','X','Generic',TRUE,TRUE),
('CMV','BAL','BAL',TRUE,TRUE),
('CMV','SEB','BAL',TRUE,TRUE),
('CMV','SET','BAL',TRUE,TRUE),
('EBV','E','WB',TRUE,TRUE),
('EBV','EP','PL (plasma)',TRUE,TRUE),
('EBV','BAL','Generic',TRUE,TRUE),
('EBV','SEB','Generic',TRUE,TRUE),
('EBV','SET','Generic',TRUE,TRUE),
('EBV','X','Generic',TRUE,TRUE),
('HEV','EP','PL (plasma)',FALSE,TRUE),
('HEV','St','ST (stool)',FALSE,TRUE),
('HEV','S','Generic',FALSE,TRUE),
('HEV','X','Generic',FALSE,TRUE),
('PNJ','BAL','BAL',TRUE,TRUE),
('PNJ','SPU','SP (sputum)',TRUE,TRUE),
('PNJ','SEB','SP (sputum)',TRUE,TRUE),
('PNJ','SET','SP (sputum)',TRUE,TRUE),
('PNJ','X','Generic',TRUE,TRUE),
('MTB','SPU','SP (sputum)',TRUE,TRUE),
('MTB','BAL','BAL',TRUE,TRUE),
('MTB','SEB','BAL',TRUE,TRUE),
('MTB','SE','BAL',TRUE,TRUE),
('MTB','SET','BAL',TRUE,TRUE),
('MTB','U','U (urine)',TRUE,TRUE),
('MTB','PU','CL (cavitary liquid)',TRUE,TRUE),
('MTB','PUA','CL (cavitary liquid)',TRUE,TRUE),
('MTB','PUP','CL (cavitary liquid)',TRUE,TRUE),
('MTB','GEW','B (biopsy)',TRUE,TRUE),
('MTB','PE','B (biopsy)',TRUE,TRUE),
('MTB','MAG','GA (gastric aspirate)',TRUE,TRUE),
('MTB','X','Generic',TRUE,TRUE),
('MDR','GEW','B (biopsy)',FALSE,TRUE),
('MDR','PE','B (biopsy)',FALSE,TRUE),
('MDR','BAL','BAL',FALSE,TRUE),
('MDR','SEB','BAL',FALSE,TRUE),
('MDR','SE','BAL',FALSE,TRUE),
('MDR','SET','BAL',FALSE,TRUE),
('MDR','PU','CL (cavitary liquid)',FALSE,TRUE),
('MDR','PUA','CL (cavitary liquid)',FALSE,TRUE),
('MDR','PUP','CL (cavitary liquid)',FALSE,TRUE),
('MDR','MAG','GA (gastric aspirate)',FALSE,TRUE),
('MDR','SPU','SP (sputum)',FALSE,TRUE),
('MDR','U','U (urine)',FALSE,TRUE),
('MDR','X','Generic',FALSE,TRUE),
('RB','BAL','BAL',FALSE,TRUE),
('RB','X','Generic',FALSE,TRUE);
