apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcr-backend
  namespace: pcr
  labels:
    app: pcr-backend
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcr-backend
  template:
    metadata:
      labels:
        app: pcr-backend
        tier: backend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - image: kallepan/pcr-backend
          imagePullPolicy: Always
          name: pcr-backend
          envFrom:
            - secretRef:
                name: oe-secrets
          ports:
            - containerPort: 8080
              name: gin
          readinessProbe:
            httpGet:
              path: /api/v1/ping
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /api/v1/ping
              port: 8080
            periodSeconds: 30
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"
          securityContext:
            allowPrivilegeEscalation: false