CREATE TABLE analyses (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    analyt VARCHAR(5) NOT NULL,
    material VARCHAR(50) NOT NULL,
    assay VARCHAR(50) NOT NULL,
    ready_mix BOOLEAN NOT NULL
);

CREATE TABLE samples (
    tagesnummer VARCHAR(12) PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP,

    created_by UUID NOT NULL
);

CREATE TABLE sampleanalyses (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    run VARCHAR(20) NULL,
    device VARCHAR(20) NULL,
    
    created_at TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP,

    analysis_id bigint NOT NULL,
    sample_id VARCHAR(12) NOT NULL,
    created_by UUID NOT NULL
);

ALTER TABLE samples ADD CONSTRAINT fk_sample_created_by FOREIGN KEY (created_by) REFERENCES users(user_id) DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS fk_sample_created_by IMMEDIATE;
ALTER TABLE analyses ADD CONSTRAINT unique_analyte UNIQUE (analyt, material, assay);

-- creates an index of certain tables to speed up queries
CREATE INDEX idx_sampleanalyses_analysis_id ON sampleanalyses (analysis_id);
CREATE INDEX idx_sampleanalyses_sample_id ON sampleanalyses (sample_id);
CREATE INDEX idx_samples_tagesnummer ON samples (tagesnummer);
CREATE INDEX idx_samples_tagesnummer_like ON samples (tagesnummer varchar_pattern_ops);

-- Create foreign key constraints
ALTER TABLE sampleanalyses ADD CONSTRAINT fk_sampleanalyses_analysis_id FOREIGN KEY (analysis_id) REFERENCES analyses(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sampleanalyses ADD CONSTRAINT fk_sampleanalyses_sample_id FOREIGN KEY (sample_id) REFERENCES samples(tagesnummer) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sampleanalyses ADD CONSTRAINT fk_sampleanalyses_created_by FOREIGN KEY (created_by) REFERENCES users(user_id) DEFERRABLE INITIALLY DEFERRED;
COMMIT;