INSERT INTO analyses (
    analyt,
    material,
    assay,
    ready_mix
)
VALUES 
('CMV','EP','PL (plasma)',TRUE),
('CMV','E','WB (whole blood)',TRUE),
('CMV','Liq','CSF',TRUE),
('CMV','U','U (urine)',TRUE),
('CMV','ABN','BS (buccal swab)',TRUE),
('CMV','AB','BS (buccal swab)',TRUE),
('CMV','Fruchtwasser','AF (amniotic fluid)',TRUE),
('CMV','Stuhl','Generic',TRUE),
('CMV','VB','Generic',TRUE),
('CMV','S','Generic',TRUE),
('CMV','X','Generic',TRUE),
('CMV','BAL','BAL',TRUE),
('CMV','SEB','BAL',TRUE),
('CMV','SET','BAL',TRUE),
('EBV','E','WB',TRUE),
('EBV','EP','PL (plasma)',TRUE),
('EBV','BAL','Generic',TRUE),
('EBV','SEB','Generic',TRUE),
('EBV','SET','Generic',TRUE),
('EBV','X','Generic',TRUE),
('HEV','EP','PL (plasma)',FALSE),
('HEV','St','ST (stool)',FALSE),
('HEV','S','Generic',FALSE),
('HEV','X','Generic',FALSE),
('PNJ','BAL','BAL',TRUE),
('PNJ','SPU','SP (sputum)',TRUE),
('PNJ','SEB','SP (sputum)',TRUE),
('PNJ','SET','SP (sputum)',TRUE),
('PNJ','X','Generic',TRUE),
('MTB','SPU','SP (sputum)',TRUE),
('MTB','BAL','BAL',TRUE),
('MTB','SEB','BAL',TRUE),
('MTB','SE','BAL',TRUE),
('MTB','SET','BAL',TRUE),
('MTB','U','U (urine)',TRUE),
('MTB','PU','CL (cavitary liquid)',TRUE),
('MTB','PUA','CL (cavitary liquid)',TRUE),
('MTB','PUP','CL (cavitary liquid)',TRUE),
('MTB','GEW','B (biopsy)',TRUE),
('MTB','PE','B (biopsy)',TRUE),
('MTB','MAG','GA (gastric aspirate)',TRUE),
('MTB','X','Generic',TRUE),
('MDR','GEW','B (biopsy)',FALSE),
('MDR','PE','B (biopsy)',FALSE),
('MDR','BAL','BAL',FALSE),
('MDR','SEB','BAL',FALSE),
('MDR','SE','BAL',FALSE),
('MDR','SET','BAL',FALSE),
('MDR','PU','CL (cavitary liquid)',FALSE),
('MDR','PUA','CL (cavitary liquid)',FALSE),
('MDR','PUP','CL (cavitary liquid)',FALSE),
('MDR','MAG','GA (gastric aspirate)',FALSE),
('MDR','SPU','SP (sputum)',FALSE),
('MDR','U','U (urine)',FALSE),
('MDR','X','Generic',FALSE),
('RB','BAL','BAL',FALSE),
('RB','X','Generic',FALSE);
