apiVersion: v1
kind: Service
metadata:
  name: pcr-backend
  namespace: pcr
  labels:
    app: pcr-backend
    tier: backend
spec:
  selector:
    app: pcr-backend
    tier: backend
  ports:
    - protocol: TCP
      name: gin
      port: 80
      targetPort: 8080